language: csharp
solution: ./RazorCore/MonoRazorCore.sln

install:
  - nuget restore ./RazorCore/MonoRazorCore.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./RazorCore/MonoRazorCore.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./RazorCore/bin/Release/MonoRazorCore.dll