language: csharp
solution: RazorCore/MonoRazorCore.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore RazorCore/MonoRazorCore.sln
after_script:
  - nunit-console RazorCore/bin/Release/MonoRazorCore.dll